apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
- deploy.yml

patchesJson6902:
  {% for n in [
      "certificaterequests.cert-manager.io",
      "certificates.cert-manager.io",
      "challenges.acme.cert-manager.io",
      "clusterissuers.cert-manager.io",
      "issuers.cert-manager.io",
      "orders.acme.cert-manager.io"
  ] %}
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: {{ n }}
  path: remove-status-patch.yml
{% endfor %}
